// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7lS7TP21WEkkpehjK-WcylxHX6i2qszs',
    appId: '1:1096260298526:web:c35401feeabe0bbffd8b0f',
    messagingSenderId: '1096260298526',
    projectId: 'joblink-7aebf',
    authDomain: 'joblink-7aebf.firebaseapp.com',
    storageBucket: 'joblink-7aebf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQe3_CtTbieKKoaQoJpanbEveaHMfzIIA',
    appId: '1:1096260298526:android:4432a161ab6e9469fd8b0f',
    messagingSenderId: '1096260298526',
    projectId: 'joblink-7aebf',
    storageBucket: 'joblink-7aebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1JEsNohrnHu5quw95lLsPqGGk73GiIaM',
    appId: '1:1096260298526:ios:588154bbea75c50cfd8b0f',
    messagingSenderId: '1096260298526',
    projectId: 'joblink-7aebf',
    storageBucket: 'joblink-7aebf.firebasestorage.app',
    iosBundleId: 'com.example.joblinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1JEsNohrnHu5quw95lLsPqGGk73GiIaM',
    appId: '1:1096260298526:ios:588154bbea75c50cfd8b0f',
    messagingSenderId: '1096260298526',
    projectId: 'joblink-7aebf',
    storageBucket: 'joblink-7aebf.firebasestorage.app',
    iosBundleId: 'com.example.joblinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7lS7TP21WEkkpehjK-WcylxHX6i2qszs',
    appId: '1:1096260298526:web:7342aef6d8c298b0fd8b0f',
    messagingSenderId: '1096260298526',
    projectId: 'joblink-7aebf',
    authDomain: 'joblink-7aebf.firebaseapp.com',
    storageBucket: 'joblink-7aebf.firebasestorage.app',
  );
}
